version: '3.1'

services:
  badgeuse-web:
    build:
      context: client
    ports:
      - 85:80
    depends_on:
      - badgeuse-node


  badgeuse-node:
    build:
      context: .
    environment:
      - PORT_ANGULAR=85
      - HOST_ANGULAR=145.239.32.254 #ipLocal adress
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mariadb:
    image: library/mariadb:latest
    volumes:
      - ./BDD/data:/var/lib/mysql
      - ./BDD/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "uhaSQL"
      MYSQL_PASSWORD: "uha"
      MYSQL_DATABASE: "badgeuse"
    expose:
      - 3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 86:80
