version: '3.1'

services:
  badgeuse-web:
    build:
      context: client
    ports:
      - ${PORT_ANGULAR}:80
    depends_on:
      - badgeuse-node
    env_file:
      - ./.env


  badgeuse-node:
    build:
      context: .
    ports:
      - ${PORT_BACK}:8080
    depends_on:
      - mariadb
    env_file:
      - ./.env

  mariadb:
    image: library/mariadb:latest
    volumes:
      - ./BDD/data:/var/lib/mysql:z
      - ./BDD/init.d:/docker-entrypoint-initdb.d:z
    env_file:
      - ./.env
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
